### ISSUE TITLE
Start replacing redudant code with pn_push()

### ISSUE THREAD

**Issue by atoms118** [atoms118/libpolynet-c#23]
Pretty self explanatory; replace all the push code with the pn_push() function to save precious lines and human readability

**Comment by bvs23bkv33** [comment]
following functions should utilise pn_push:
1) in certificate.c:
- pn_add_trust, which manages PN_CERTIFICATENAME **trusted_certificates field of PN_SERTIFICATESSTATE,
- pn_add_certificate, which manages PN_CERTIFICATE **certificate_buffer field of PN_SERTIFICATESSTATE,
- pn_add_tmp_certificate, which manages PN_CERTIFICATE **tmp_certificate_buffer field of PN_SERTIFICATESSTATE,
2) in packet.c:
- pn_add_packet_to_buffer, which manages PN_PACKET **buffer field of PN_PACKETBUFFER,
- pn_add_packet_buffer, which manages PN_PACKETBUFFER **packet_buffers field of PN_PACKETSSTATE,
3) in route.c:
- pn_add_route, which manages PN_ROUTE **routes field of PN_ROUTESSTATE,
- pn_add_tmp_route, which manages PN_ROUTE **tmp_routes field of PN_ROUTESSTATE,
- pn_add_neighbour, which manages PN_NEIGHBOUR **neighbours field of PN_ROUTESSTATE,
4) in service.c:
- pn_add_service, which manages PN_SERVICE **services field of PN_SERVICESSTATE.

do i understand this correctly?

**Comment by atoms118** [comment]
Yep, this seems right. If you plan on taking care of this you can assign yourself to the issue

Thanks again for the help!

**Comment by bvs23bkv33** [comment]
see #33

**Comment by atoms118** [comment]
Ok, I'm going to unassign bvs23bkv33 until he gets back from vacation so somebody else can (possibly) get it done
